[versions]
precompose = "1.6.2"
snakeyaml = "2.3"
gson = "2.11.0"
kermit = "2.0.5"
central = "1.2.5"
maleficextensions = "1.2.0"
dokka = "2.0.0"
compose = "1.8.0-alpha01"
kotlin = "2.1.0"
kotlinter = "5.0.1"

[libraries]
precompose = { module = "moe.tlaster:precompose", version.ref = "precompose" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
malefic-extensions = { module = "xyz.malefic.compose:ext", version.ref = "maleficextensions" }

[plugins]
compose-kotlin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
central = { id = "cn.lalaki.central", version.ref = "central"}
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
